import Head from 'next/head'
import Image from 'next/image'
import { ReactElement } from 'react'
import DashboardLayout from '../layouts/dashboard'
import styles from '../styles/Home.module.css'

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <DashboardLayout>
      {page}
    </DashboardLayout>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bug Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Hello World

     
    </div>
  )
}
